---

- name: Setup (n)vim
  hosts: localhost

  tasks:
  - name: Install (n)vim
    homebrew:
      name: '{{ item }}'
    with_items:
      - vim
      - nvim

  - name: Setup vim config
    file:
      src: '{{ansible_facts.env.PWD}}/{{item}}'
      dest: '~/.{{item}}'
      state: link
    with_items:
      - vimrc
      - vim

  - name: Setup nvim config
    file:
      src: '{{ansible_facts.env.PWD}}/{{item}}'
      dest: '~/.config/{{item}}'
      state: link
    with_items:
      - nvim
