---

- name: Setup vim
  hosts: localhost

  tasks:
  - name: Install vim
    homebrew:
      name: vim

  - name: Setup vim config
    file:
      src: '{{ansible_facts.env.PWD}}/{{item}}'
      dest: '~/.{{item}}'
      state: link
    with_items:
      - vimrc
      - vim
