set nocompatible        "Run in vim mode not vi

set number              "Display line numbers

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab           "Replace tabs with spaces

colorscheme railscasts

set cursorline          "Highlight current line
set hidden              "Reuse Window for multiple buffers

if has('gui_running')
  set lines=100         "Set window height
  set columns=120       "Set window width

  set guioptions-=T     "Remove toolbar
  set guioptions-=r     "Remove right-hand scroll bar
endif
